import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import FloatingButton from '@/components/FloatingButton';

export const metadata = {
  title: 'Intersport',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="shadow-lg">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
